fix brunch-config.js in installer to be compatible with 2.9.1
In brunch 2.8.2 the following is valid in autoRequire:

  "js/app.js": ["app"]

In brunch 2.9.1 this has to be:

  "js/app.js": ["app"]

Otherwise the following error will be logged and the JavaScript will not
execute:

 > Uncaught Error: Cannot find module 'js/app' from '/'

The difference in the compiled JavaScript prior to this change was:

    $ diff /tmp/app-broken.js /tmp/app-working.js
    151c151
    < require.register("js/app.js", function(exports, require, module) {
    ---
    > require.register("app.js", function(exports, require, module) {